# -*- coding: utf-8 -*-
"""
/***************************************************************************
 remove_filter
                                 A QGIS plugin
 it removes the temp filter applied on vector layers & vector tile layers
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-02-11
        copyright            : (C) 2025 by Vishnudurga
        email                : post2vd@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):
    from .remove_temp_filter import RemoveTempFilterPlugin
    return RemoveTempFilterPlugin(iface)
